server:
  port: 8101
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/riverluoo/riverluoo.github.io
          searchPaths: repo
          username: riverluoo
          password: xxxxxx
      label: master
  rabbitmq:
    host: 39.96.69.79
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtualHost: /
    publisherConfirms: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh